event_app/urls.py
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.event, name='event'),
    path('join-event/', views.join_event, name='join_event'),
    path('participate/', views.participate, name='participate'),
]

form_app/urls.py
from django.conf.urls import url
from django.urls import re_path
from .views import index,add_member

urlpatterns = [
    re_path('registration/', index, name='registration'),
	re_path('add_member/', add_member, name = 'add_member')
]

news_app/urls.py
from django.conf.urls import url
from .views import news
#url for app
urlpatterns = [
 url(r'^$', news, name='news'),
]

ppw_tugas/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include(('form_app.urls','form_app'), namespace = 'member')),
    path('', include(('home_app.urls','home_app'), namespace= 'home')),
#path('accounts/', include('form_app.urls'), namespace='accou'),
    path('events/', include(('event_app.urls','event_app'), namespace='event')),
    path('news/', include(('news_app.urls', 'news_app'), namespace='news')),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
	<head>
		<meta charset="UTF-8">
		{% block title %}<title>Student Union </title>{% endblock %}
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" integrity="sha384-pjaaA8dDz/5BgdFUPX6M/9SUZv4d12SUPF0axWc+VRZkx5xU3daN+lYb49+Ax+Tl" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}">
		<link href="https://fonts.googleapis.com/css?family=Roboto+Mono" rel="stylesheet">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
		{% block extrahead %}
		{% endblock %}
	</head>
	<body>
		<header>
			<a href="{% url 'home_app:index' %}"><img src="{% static 'img/logo.png' %}" alt="logo" style="height:48px; width:auto; margin: 10px 10px 10px 10px;" ></a>
			<input type="checkbox" id="nav-toggle" class="nav-toggle">
			<nav>
			<ul>
			<li><a href="{% url 'news:news' %}">NEWS</a></li>
			<li><a href="{% url 'event:event' %}">EVENT</a></li>
			<li><a href="{% url 'member:registration' %}">REGISTER</a></li>
			<li><a href="{% url 'event:join_event' %}">JOIN EVENT</a></li>
			</ul>
			</nav>
			<label for="nav-toggle" class="nav-toggle-label">
			<span></span>
			</label>
	</header>
			{% block content %}
			{% endblock %}
	</body>

	<!-- Footer -->
	<footer class="footer-distributed">

				<div class="footer-center">

					<h3 class="footer-text">Student Union</h3>



					<p class="footer-company-name" style="margin-top:20px;">Studen Union &copy; 2018</p>
				</div>

				<div class="footer-center">

					<div>
						<i class="fa fa-instagram"></i>
						<p class="footer-text">@studentunion</p>
					</div>

					<div>
						<i class="fa fa-whatsapp"></i>
						<p class="footer-text">+62 812-3456-789</p>
					</div>

					<div>
						<i class="fa fa-envelope"></i>
						<p class="footer-text" style="color:white;"><p>studentunion@gmail.com</p></p>
					</div>

					<div>
						<i class="fa fa-twitter"></i>
						<p class="footer-text">@studentunion</p>
					</div>

				</div>

				<div class="footer-right">

					<p class="footer-company-about">
						<span>About the company</span>
						Student Union is a company that helps students to create and join events
					</p>



				</div>

			</footer>
  <!-- Footer -->
</html>