event_app/urls.py
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.event, name='event'),
    path('join-event/', views.join_event, name='join_event'),
    path('participate/', views.participate, name='participate'),
]

form_app/urls.py
from django.conf.urls import url
from django.urls import re_path
from .views import index,add_member

urlpatterns = [
    re_path('registration/', index, name='registration'),
	re_path('add_member/', add_member, name = 'add_member')
]

ppw_tugas/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include(('form_app.urls','form_app'), namespace = 'member')),
    path('', include(('home_app.urls','home_app'), namespace= 'home')),
#path('accounts/', include('form_app.urls'), namespace='accou'),
    path('events/', include(('event_app.urls','event_app'), namespace='event')),
    path('news/', include(('news_app.urls', 'news_app'), namespace='news')),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

event_app/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    nama_event = models.CharField(max_length=100)
    tanggal = models.DateField()
    deskripsi = models.TextField()
    foto_event = models.TextField()


    def __str__(self):
        return self.nama_event



class Participant(models.Model):
    nama = models.CharField(max_length = 100)
    username = models.CharField(max_length=50, unique = True)
    email = models.EmailField(unique = True)
    event = models.CharField(max_length=100)

    def __str__(self):
        return self.nama

event_app/forms.py
from django import forms
from .models import Event

class ParticipantForm(forms.Form):

    attrs= {
        'class' : 'form-control',
    }

    name_attrs = {
        'class' : 'form-control'
    }

    email_attrs = {
        'class' : 'form-control'
    }

    nama = forms.CharField(max_length=100, required=True, widget= forms.TextInput(attrs=name_attrs))
    username = forms.CharField(required = True, max_length = 100, widget = forms.TextInput(attrs=attrs))
    email = forms.EmailField(required=True, widget= forms.TextInput(attrs=email_attrs))
    event = forms.ModelChoiceField(queryset=Event.objects.all(), label='Event', widget=forms.Select)

event_app/views.py
from django.shortcuts import render
from .models import Event, Participant
from .forms import ParticipantForm
from django.http import HttpResponseRedirect
from . import forms
# Create your views here.

response ={}
def event(request):
    event = Event.objects.all()
    participant = Participant.objects.all()
    response['all_event'] = event
    response['participant'] = participant
    html = 'event.html'
    return render(request, html, response)


def join_event(request):
    response['join_event'] = ParticipantForm
    html = 'join-event.html'
    return render(request, html, response)

def participate(request):
	form = forms.ParticipantForm(request.POST)
	# objek_member = Event.objects.values_list('username')
	if (form.is_valid()):
		response['nama'] = request.POST['nama']
		response['username'] = request.POST['username']
		response['email'] = request.POST['email']
		response['event'] = form.cleaned_data['event']
		member = Participant(nama = response['nama'], username = response['username'], email = response['email'], event = response['event'])
		member.save()
		return HttpResponseRedirect('/events/')
	else:
		form = forms.ParticipantForm()

	return render(request, 'event.html', response)

event_app/templates/event.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/event.css' %}">
{% endblock %}
{% block content %}

<div class="container-text" style="background-color:#127FB9; height:196px;">
    <p class="event-test">EVENT</p>
</div>
<div class="event-cotent">
    <div class="table-responsive all-table">
        <table style="width:100%;">
            {% if all_event %}
            <h1>Kegiatan yang ada</h1>
            <tr>
                <th>Nama Event</th>
                <th>Tanggal</th>
                <th>Deskripsi</th>
                <th>Peserta</th>
            </tr>
            <tbody>
                {% for i in all_event %}
                <tr class="table-event">
                    <td>{{i.nama_event}}</td>
                    <td>{{i.tanggal}}</td>
                    <td>{{i.deskripsi}}</td>
                    <td>
                    {% for j in participant %}
                    {% if j.event == i.nama_event %}
                        <p>- {{j.nama}} </p>

                    {% endif %}
                    {% endfor %}
                    <hr style="width:100%">
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            {% endif %}
        </table>
    </div>
</div>


{% endblock %}

event_app/templates/join-event.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="jumbotron" style="background-color:#127FB9; text-align: center">
    <h1 style="font-size : 50px"> JOIN EVENT </h1>
</div>
<section class="container" id="projects">
    <div class="row">
        <div class = "col-md-3">
        </div>
        <div class="col-md-6 col-md-offset-6">
            <div class="form-regis" style="left:50%;">
                <form id="form" method="POST" action="{% url 'event:participate' %}">
                    {% csrf_token %}
                    {{join_event}}
                    <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
                </form>
            </div>
        </div>
    </div>
    <br>
    <button type="button" class="btn btn-info" onclick="window.location.href='/'"> Back </button>
</section>
{% endblock %}